apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-etcd
#  namespace: backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjobreport"
        spec:
          serviceAccountName: backup-etcd
          containers:
          - name: backup-etcd
            image: docker.io/christiancarle/etcd_backup:latest
            args:
            - /bin/sh 
            - -c
            volumeMounts:
            - mountPath: /var/lib/etcd/member/snap
              name: etcd-db
            - mountPath: /etc/etcd
              name: etcd-config
            - mountPath: /nas_etcd
              name: etcd-nas
            securityContext:
              privileged: true
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/master: "true"
#          tolerations:
#          - effect: NoSchedule
#            operator: Exists
          restartPolicy: OnFailure
          volumes:
          - name: etcd-db
            hostPath:
              path: /var/lib/etcd/member/snap
#              type: DirectoryOrCreate
          - name: etcd-config
            hostPath:
              path: /etc/etcd
          - name: etcd-nas
            nfs:
              path: /9413-APP-NASMASPAppLogs
              server: gotsnm5104.got.volvocars.net
